### PR TITLE
Code review: private events project

### PR DESCRIPTION
**Pull request by bafiam**
#### What does this PR do?
1. Consist of the working code of the private events
2. Users can login/signup and be in a position to create events.
3. They can as well invite users into an event
#### How should this be manually tested?
Clone the repo then navigate to the project directory,:
- run `rspec` on terminal to run the test cases

### CODE REVIEW

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Under Review By Tolulope Olusakin(TSE)
Please check on this in a few minutes for some feedback! :+1:

**Review by nikasulo — CHANGES_REQUESTED** [review]
# This is fantastic work! @bafiam and @simoxsimo :medal_military: 
Please consider my comment below, make the necessary change and request another review. I wish you the very best and see you at the top :rocket: 

#### Event Controller Show Action
Please consider that as per requirements, the show action of the events controller should do the following:

* Lists events created by the current user
screenshot

* Lists events previously attended by the user using an event scope
screenshot

* Lists upcoming events previously attended by the current user
screenshot

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by simoxsimo** [comment]
## Thank you for reviewing our project.
Since we already tackled the issues sited by the code review, we decided to include a seed file to make it easier to review.
1 - After running the seed file, log-in with this email (admin@microverse.com) and check out "Booked Events" navigation link.
Capture-1

2 & 3 - You can check at "Profile page"
Capture - 2

**Review by nikasulo — CHANGES_REQUESTED** [review]
# Great work team! :rocket: 
I can see the functionality works, however, the required implementation stipulates that the objects for each one of those(created events, upcoming and past events) is created in the controller. Please look into making this change.

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Comment by bafiam** [comment]
This was the main pointer to our approach **Have your controller call separate model methods to retrieve each,** so our controller 
``` 
 def show
    @user = User.find_by(id: params[:id])
    @upcoming_events = @user.upcoming_events
    @prev_events = @user.previous_events
  end
```
calls a instance methods in the User model
```
class User < ApplicationRecord
  has_many :events, foreign_key: 'creator_id', class_name: 'Event'
  has_many :bookings, foreign_key: 'attendee_id'
  has_many :attended_events, through: :bookings, source: :attended_event

  def previous_events
    attended_events.where('date < ?', Time.now)
  end

  def upcoming_events
    attended_events.where('date >= ?', Time.now)
  end
end
```
**reference**


The same approach was used when getting past and upcoming events but using scope as stipulated in the instructions.
The model
```
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User', optional: true
  has_many :bookings, foreign_key: 'attended_event_id'
  has_many :attendees, through: :bookings, source: :attendee

  scope :past, -> { where('date < ?', Time.now) }
  scope :upcoming, -> { where('date >= ?', Time.now) }
end
```
The controller
```
  def index
    @past = Event.past
    @upcoming = Event.upcoming
  end
```
**reference**

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello, I really love your work. The code is so clean and simple.
Only one thing to do. Please add indexes in your **Bookings** table for foreign keys.

After that, please submit a new code review request.
Thanks.

Mael FOSSO

**Review by nikasulo — APPROVED** [review]
# Great work @bafiam and @simoxsimo :medal_military: 
You have done really well building this! Please consider my optional comment below as it will make database tasks more performant. That being said, you may merge and keep moving forward! :rocket: I wish you the best and see you at the top.

#### [OPTIONAL]
Please index your foreign key in the bookings database as pointed out by my colleague

##### Think I missed something? Need some help with this or any of your projects? Please feel free to reach out to me on [Twitter](https://twitter.com/oluwadamilareo_) or [Instagram](https://instagram.com/oluwadamilare_olusakin), even if you just want to chat and I will respond to you as soon as I can.

**Pull request merged**
